import { Input } from './input';
import { RawInputListener } from './raw-input-listener';

export abstract class KeyInput implements Input {

  static KEY_UNKNOWN: number = 0x00;

  static KEY_ESCAPE: number = 0x01;
  static KEY_1: number = 0x02;
  static KEY_2: number = 0x03;
  static KEY_3: number = 0x04;
  static KEY_4: number = 0x05;
  static KEY_5: number = 0x06;
  static KEY_6: number = 0x07;
  static KEY_7: number = 0x08;
  static KEY_8: number = 0x09;
  static KEY_9: number = 0x0A;
  static KEY_0: number = 0x0B;
  static KEY_MINUS: number = 0x0C;
  static KEY_EQUALS: number = 0x0D;
  static KEY_BACK: number = 0x0E;
  static KEY_TAB: number = 0x0F;
  static KEY_Q: number = 0x10;
  static KEY_W: number = 0x11;
  static KEY_E: number = 0x12;
  static KEY_R: number = 0x13;
  static KEY_T: number = 0x14;
  static KEY_Y: number = 0x15;
  static KEY_U: number = 0x16;
  static KEY_I: number = 0x17;
  static KEY_O: number = 0x18;
  static KEY_P: number = 0x19;
  static KEY_LBRACKET: number = 0x1A;
  static KEY_RBRACKET: number = 0x1B;
  static KEY_RETURN: number = 0x1C;
  static KEY_LCONTROL: number = 0x1D;
  static KEY_A: number = 0x1E;
  static KEY_S: number = 0x1F;
  static KEY_D: number = 0x20;
  static KEY_F: number = 0x21;
  static KEY_G: number = 0x22;
  static KEY_H: number = 0x23;
  static KEY_J: number = 0x24;
  static KEY_K: number = 0x25;
  static KEY_L: number = 0x26;
  static KEY_SEMICOLON: number = 0x27;
  static KEY_APOSTROPHE: number = 0x28;
  static KEY_GRAVE: number = 0x29;
  static KEY_LSHIFT: number = 0x2A;
  static KEY_BACKSLASH: number = 0x2B;
  static KEY_Z: number = 0x2C;
  static KEY_X: number = 0x2D;
  static KEY_C: number = 0x2E;
  static KEY_V: number = 0x2F;
  static KEY_B: number = 0x30;
  static KEY_N: number = 0x31;
  static KEY_M: number = 0x32;
  static KEY_COMMA: number = 0x33;
  static KEY_PERIOD: number = 0x34;
  static KEY_SLASH: number = 0x35;
  static KEY_RSHIFT: number = 0x36;
  static KEY_MULTIPLY: number = 0x37;
  static KEY_LMENU: number = 0x38;
  static KEY_SPACE: number = 32;
  static KEY_CAPITAL: number = 0x3A;
  static KEY_F1: number = 0x3B;
  static KEY_F2: number = 0x3C;
  static KEY_F3: number = 0x3D;
  static KEY_F4: number = 0x3E;
  static KEY_F5: number = 0x3F;
  static KEY_F6: number = 0x40;
  static KEY_F7: number = 0x41;
  static KEY_F8: number = 0x42;
  static KEY_F9: number = 0x43;
  static KEY_F10: number = 0x44;
  static KEY_NUMLOCK: number = 0x45;
  static KEY_SCROLL: number = 0x46;
  static KEY_NUMPAD7: number = 0x47;
  static KEY_NUMPAD8: number = 0x48;
  static KEY_NUMPAD9: number = 0x49;
  static KEY_SUBTRACT: number = 0x4A;
  static KEY_NUMPAD4: number = 0x4B;
  static KEY_NUMPAD5: number = 0x4C;
  static KEY_NUMPAD6: number = 0x4D;
  static KEY_ADD: number = 0x4E;
  static KEY_NUMPAD1: number = 0x4F;
  static KEY_NUMPAD2: number = 0x50;
  static KEY_NUMPAD3: number = 0x51;
  static KEY_NUMPAD0: number = 0x52;
  static KEY_DECIMAL: number = 0x53;
  static KEY_F11: number = 0x57;
  static KEY_F12: number = 0x58;
  static KEY_F13: number = 0x64;
  static KEY_F14: number = 0x65;
  static KEY_F15: number = 0x66;
  static KEY_KANA: number = 0x70;
  static KEY_CONVERT: number = 0x79;
  static KEY_NOCONVERT: number = 0x7B;
  static KEY_YEN: number = 0x7D;
  static KEY_NUMPADEQUALS: number = 0x8D;
  static KEY_CIRCUMFLEX: number = 0x90;
  static KEY_AT: number = 0x91;
  static KEY_COLON: number = 0x92;
  static KEY_UNDERLINE: number = 0x93;
  static KEY_KANJI: number = 0x94;
  static KEY_STOP: number = 0x95;
  static KEY_AX: number = 0x96;
  static KEY_UNLABELED: number = 0x97;
  static KEY_PRTSCR: number = 0x9A;
  static KEY_NUMPADENTER: number = 0x9C;
  static KEY_RCONTROL: number = 0x9D;
  static KEY_NUMPADCOMMA: number = 0xB3;
  static KEY_DIVIDE: number = 0xB5;
  static KEY_SYSRQ: number = 0xB7;
  static KEY_RMENU: number = 0xB8;
  static KEY_PAUSE: number = 0xC5;
  static KEY_HOME: number = 0xC7;
  static KEY_UP: number = 0xC8;
  static KEY_PRIOR: number = 0xC9;
  static KEY_PGUP: number = KeyInput.KEY_PRIOR;

  static KEY_LEFT: number = 0xCB;
  static KEY_RIGHT: number = 0xCD;
  static KEY_END: number = 0xCF;
  static KEY_DOWN: number = 0xD0;
  static KEY_NEXT: number = 0xD1;
  static KEY_PGDN: number = KeyInput.KEY_NEXT;

  static KEY_INSERT: number = 0xD2;
  static KEY_DELETE: number = 0xD3;

  static KEY_LMETA : number = 0xDB;

  static KEY_RMETA: number = 0xDC;

  static KEY_APPS: number = 0xDD;
  static KEY_POWER: number = 0xDE;
  static KEY_SLEEP: number = 0xDF;

  static KEY_LAST: number = 0xE0;

  public abstract destroy(): void;
  public abstract getInputTime(): number;
  public abstract initialize(): void;
  public abstract isInitialized(): boolean;
  public abstract setInputListener(listener: RawInputListener): void;
  public abstract update(): void;
}
